# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-05-23 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('company', models.CharField(max_length=30)),
                ('M_date', models.DateField()),
                ('Exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='restuarent',
            fields=[
                ('adress1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application3.Place')),
            ],
        ),
        migrations.CreateModel(
            name='waiter',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application3.restuarent')),
            ],
        ),
    ]
