# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-05-23 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reporters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=28)),
                ('last_name', models.CharField(max_length=30)),
                ('p1', models.CharField(max_length=40)),
                ('p2', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='restuarent',
            name='adress1',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='name',
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('headlines', models.CharField(max_length=50)),
                ('publice_date', models.DateField()),
                ('reporters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application3.reporters')),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='restuarent',
        ),
        migrations.DeleteModel(
            name='waiter',
        ),
    ]
